### ISSUE TITLE
Respons

### ISSUE THREAD

**Issue by andsju** [Shazia-Nasreen/HTML_AND_GIT#1]
Respons Case 2 Grundläggande CSS
 
Godkänd: nej
 
Hej Shazia!
Här kommer respons till case 2. Responsen utgår från de kriterier som finns för grundläggande krav, se 

https://github.com/Glimakra-Webbutvecklare-2024/Case-2-CSS

---

Samtliga sidor ska

- använda samma externa css fil
- använda flex och|eller grid för layout av ytor
- använda elementen header, nav och footer som gör att användaren kan navigera mellan sidor och uppleva en enhetlig layout

Din kod ska

- visa att du kan använda selektorer för element, class och id
- ha exempel på kod som använder en pseudoklass - ex :hover
- vara versionshanterad på GitHub, du ska ha gjort minst 10 commits över tid (du ska kunna visa att du arbetat med koden under flertalet arbetsdagar)
- följa en god namngivningsprincip för filer, mappar, klasser och id (ex latinska tecken, bindestreck, understreck, engelska namn)
- på någon av sidorna visa kvadratiska bilder (som ett flöde från Instagram typ) som presenteras på ett snyggt sätt.

---

I individuell respons väljer vi lärare fokusera på vissa delar. I det här caset: 

- Kodkvalité - struktur, kommentarer
- CSS selektorer - namngivning, kombinera instruktioner 
- Versionshantering

I responsen kan en eller flera kommentarer och korrigeringar finnas. Kommentarer kan vara uppmuntrande där vi noterar ngt i koden. Kommentarer kan också ange ngt du kan tänka på, men som du inte behöver justera. 

Korrigeringar innebär att du måste justera ngt i ditt arbete för att bli godkänd.
 
---

Med designen du har skapat har sidorna fått en god läsbarhet. Du har använt hover när man surfar på dina sidor, och därmed visar du att du förstår hur det fungerar.

```css
        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);
        }
```

Du har visat att du förstår hur CSS fungerar genom att ange CSS egenskaper för elementet section, och olika bakgrundsfärger för olika section element med attributet id - bra!

```css

        /* Different background colors for each section */
        #om-mig {
            background-color: #e1f5fe; /* Light blue */
        }

        #min-familj {
            background-color: #ffe0b2; /* Light orange */
        }

        /* Styles for each section (card) */
        section {
            background-color: #fff; /* Default white background */
            border-radius: 8px; /* Rounded corners */
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* Light shadow for depth */
            padding: 20px; /* Padding inside sections */
            margin: 10px; /* Space between sections */
            width: calc(50% - 20px); /* Responsive width for sections */
            max-width: 500px; /* Max width for readability */
            text-align: center; /* Center-align text */
            transition: transform 0.3s, box-shadow 0.3s; /* Transition for hover effect */
        }
```

Jag uppskattar också dina kommentarer i koden. Att kommentera sin egen kod är ett bra sätt att lära sig att programmera. Sträva efter att vara konsekvent när du namnger exempelvis filer, klasser och id. Du har en fil som inleds med versal - Festival.html. Det skiljer sig från de andra filerna. Filernas namn är skrivna på både svenska och engelska - jämför history.html, galleri.html, landskap.html ...

Då det gäller namn på klasser och id finns ex *.text-holder* med engelsk namngivning och *#min-familj* med svensk namngivningsprincip.

---

Försök att redovisa nästa case i samband med att den andra i klassen redovisar. Det är bra att kunna presentera ett projekt inför andra.

---
### Kommentar 1

I grundläggande krav står det att din kod ska
- vara versionshanterad på GitHub, du ska ha gjort minst 10 commits över tid (du ska kunna visa att du arbetat med koden under flertalet arbetsdagar)

**OBS!**

I caset har du fortsatt att koda på det case som du arbetade med i modul 1. Det finns endast 1 uppdatering under perioden för case 2, och den är gjord den 23 oktober. Det innebär att ditt Git repo inte är versionshanterat. Vi lärare kan inte se vad du har förändrat under projektet. Tänk på att det är *viktigt att du skapar ett nytt repo för varje case*. 

### Korrigering 1

I grundläggande krav står det att samtliga sidor ska

- använda samma externa css fil

Ditt projekt saknar en gemensam extern CSS fil. Korrigera projektet genom att skapa en mapp med namnet styles och där ska filen style.css
Länka därefterin filen och flytta all kod som finns i elementet style på respektive sida så att den koden istället återfinns i den externa filen.

### Korrigering 2

I grundläggande krav står det att samtliga sidor ska

- använda elementen header, nav och footer som gör att användaren kan navigera mellan sidor och uppleva en enhetlig layout

Korrigera projektet så att de elementen finns på samtliga sidor. När man nu besöker de olika sidorna har du använt CSS kod och HTML struktur som gör att placering av meny och visning av meny är föränderlig. För vissa sidor är menyn centrerad på sidan, för andra vänsterjusterad. 

### Korrigering 3

I grundläggande krav står det att din kod ska 

- på någon av sidorna visa kvadratiska bilder (som ett flöde från Instagram typ) som presenteras på ett snyggt sätt.

Korrigera ngn sida som visar bilder så att den här typen av kvadratiska bilder visas där layouten skapas med CSS.

---

### Sammanfattningsvis

Jag tycker att du har löst uppgiften på ett relativt bra sätt, men du behöver korrigera din kod för att bli godkänd - se mer information ovan. När du har korrigerat koden och uppdaterat ditt repo så meddela mig i Teams. 

Shazia, om du har frågor kring responsen, eller vill ha hjälp så använd handledningstid då lärare finns tillgängliga.
